name: ASTDiff Bot
description: A GitHub Action to run RefactoringMiner and upload diff results as a .zip.
inputs:
  OAuthToken:
    description: 'OAuth Token for authentication'
    required: true
  URL:
    description: 'URL of the repository for the diff operation'
    required: true
outputs:
  artifact_url:
    description: 'URL to download the generated diff artifact'

runs:
  using: 'docker'
  image: 'docker://tsantalis/refactoringminer:latest'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
        refactoringminer diff --url "${{ inputs.URL }}" -e && \
        unzip /opt/refactoringminer/lib/RefactoringMiner-DockerBuild.jar -d /tmp/refactoringminer && \
        mkdir -p /diff/exported/web && \
        cp -r /tmp/refactoringminer/web /diff/exported/web/resources && \
        cd /diff/exported && \
        zip -r /tmp/diff-results.zip . && \
        echo "::set-output name=artifact_url::/tmp/diff-results.zip"
