name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      OAuthToken : ${{ secrets.OAUTHTOKENREAD }}
    if: ${{ github.event.head_commit.author.username != 'invalid-email-address' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.OAUTHTOKENWRITE }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: |
          npm install
          sudo apt-get install -y figlet

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Test Results - $TIMESTAMP" >> logs/testResult.txt
          figlet "Test Results" >> logs/testResult.txt
          npm test >> logs/testResult.txt 2>&1

      - name: Remove token from logs
        run: |
          echo "Removing sensitive tokens from test results..."
          # Using a delimiter to avoid conflicts with special characters in the token
          sed -i "s|${{ secrets.GITHUB_TOKEN }}|MASKED_TOKEN|g" logs/testResult.txt
          sed -i "s|${{ secrets.OAUTHTOKENREAD }}|MASKED_TOKEN|g" logs/testResult.txt
          sed -i "s|${{ secrets.OAUTHTOKENWRITE }}|MASKED_TOKEN|g" logs/testResult.txt
          sed -i "s|${{ env.OAuthToken }}|MASKED_TOKEN|g" logs/testResult.txt


      - name: Commit test results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git diff --exit-code logs || (
              git add logs
              git commit -m 'chore: update test logs'
              git push
              )
        
  build_dist:
    if: ${{ github.event.head_commit.author.username != 'invalid-email-address' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.OAUTHTOKENWRITE }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20'  # Change to your required Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Build with NCC
        run: ncc build src/index.js --license licenses.txt

      - name: Commit and push dist folder
        run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git pull
            git diff --exit-code dist || (
                git add dist
                git commit -m 'chore: update dist folder'
                git push
            )

  runActions:
    needs: build_dist
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.author.username != 'invalid-email-address' }}
    permissions:
      contents: write
    steps:
      - name: dispatch docker build
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: dispatch_tests


  release:
    needs: build_dist
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.author.username != 'invalid-email-address' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
  
      - name: Zip dist folder
        run: zip -r dist.zip dist
  
      - name: Get package version
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
  
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.OAUTHTOKENWRITE }}
