name: Test Action

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch_tests]
jobs:
  Run_Custom_Action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fromDockerHub: [true, false]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use custom action from the root
        uses: ./
        id : customAction
        with:
          URL: "https://github.com/Alluxio/alluxio/commit/9aeefcd8120bb3b89cdb437d8c32d2ed84b8a825"
          screenshot: "JAVA"
          fromDockerHub: ${{ matrix.fromDockerHub }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-${{ matrix.fromDockerHub }}
          path: ${{ steps.customAction.outputs.screenshots_path}}
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.fromDockerHub }}
          path: ${{ steps.customAction.outputs.artifact_path}}
